require: rubocop-rspec

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'config.ru'
#    - './middlewares/*'
